-- GENERATED BY MATUGEN - DO NOT EDIT
return {
    active_border   = "0xff{{colors.primary.default.hex_stripped}}",
    inactive_border = "0xff{{colors.surface_variant.default.hex_stripped}}",
    shadow          = "0x66{{colors.shadow.default.hex_stripped}}",
    text            = "0xff{{colors.on_surface.default.hex_stripped}}",

    primary    = "0xff{{colors.primary.default.hex_stripped}}",
    secondary  = "0xff{{colors.secondary.default.hex_stripped}}",
    tertiary   = "0xff{{colors.tertiary.default.hex_stripped}}",
    background = "0xff{{colors.surface.default.hex_stripped}}",
    error      = "0xff{{colors.error.default.hex_stripped}}",
}
