-- GENERATED BY MATUGEN - DO NOT EDIT
return {
    active_border   = "0xffcabeff",
    inactive_border = "0xff48454e",
    shadow          = "0x66000000",
    text            = "0xffe6e1e9",

    primary    = "0xffcabeff",
    secondary  = "0xffcac3dc",
    tertiary   = "0xffedb8cc",
    background = "0xff141318",
    error      = "0xffffb4ab",
}
