preload = /home/ms/.config/hypr/assets/wallpaper.jpg

wallpaper {
    monitor = HDMI-A-2
    path = /home/ms/.config/hypr/assets/wallpaper.jpg
    # Ensure it fills the screen
    fit_mode = cover
}

splash = false
unload_unused = true
